Taxonomy_defaults: &Taxonomy_defaults
  TYPE: "Taxonomy"
  INCLUDE_HEADER: true
  
  toName: "image"
  maxUsages: "1"
  maxWidth: "400px"
  minWidth: "400px"
  leafsOnly: "true"


fields:

  Z1:
    <<: *Taxonomy_defaults
    placeholder: 'Z1: Ichthyolith Type'
    choices:
    - 'Z1.1: Tooth'
    - 'Z1.2: Denticle'
    - 'Z1.3: Other microfossil'
    - 'Z1.4: Excess image/artifact'
    
  Type:
    <<: *Taxonomy_defaults
    placeholder: 'Type'
    apiUrl: "s3://ichthyolith/taxonomies/Type.json"

  A1:
    <<: *Taxonomy_defaults
    placeholder: 'A1: Shape'
    choices:
    - 'A1.0: Too broken to code'
    - 'A1.1: Spine'
    - 'A1.2: Cruciform'
    - 'A1.3: Circular or oval'
    - 'A1.4: Spade'
    - 'A1.5: Diamond/Rectangle/(Can be asymmetrical/kite-like)'
    - 'A1.6: Elongated Asymmetrical'
    - 'A1.7: Irregular/ other'
    - 'A1.8: "Fan-like"'
    - 'A1.9: Triangular or Arrow-like'
  A2:
    <<: *Taxonomy_defaults
    placeholder: 'A2: Spades'
    choices:
    - 'A2.0: Not a Spade/too broken to code'
    - 'A2.1: Rounded Spade'
    - 'A2.2: Squared Spade'
    - 'A2.3: Pointed Spade'
    - 'A2.4: Stretched Spade'
    - 'A2.5: Lobed Spade'
    - 'A2.6: Irregular'
  B1:
    <<: *Taxonomy_defaults
    placeholder: 'B1: Anterior shape (old Base)'
    choices:
    - 'B1.0: Too broken to code'
    - 'B1.1: Straight (flat)'
    - 'B1.2: Rounded'
    - 'B1.3: Pointed (vertex)'
    - 'B1.4: Denticle lacks directionality/Cannot discern anterior'
  B2:
    <<: *Taxonomy_defaults
    placeholder: 'B2: Anterior Margin Macro Texture Description'
    choices:
    - 'B2.0: Too broken to code'
    - 'B2.1: Smooth'
    - 'B2.2: Scalloped margin texture'
    - 'B2.3: Pointed margin texture'
    - 'B2.4: Anterior is a vertex'
  B3:
    <<: *Taxonomy_defaults
    placeholder: 'B3: Posterior Margin Micro Texture'
    choices:
    - 'B3.0: Too broken to code'
    - 'B3.1: Smooth'
    - 'B3.2: Distinct serrated'
  C1:
    <<: *Taxonomy_defaults
    placeholder: 'C1: Posterior shape (old Tip)'
    choices:
    - 'C1.0: Too broken to code'
    - 'C1.1: Straight (flat)'
    - 'C1.2: Rounded'
    - 'C1.3: Pointed (vertex)'
    - 'C1.4: Denticle lacks directionality/Cannot discern posterior'
  C2:
    <<: *Taxonomy_defaults
    placeholder: 'C2: Posterior Margin Macro Texture Description'
    choices:
    - 'C2.0: Too broken to code'
    - 'C2.1: Smooth'
    - 'C2.2: Scalloped margin texture'
    - 'C2.3: Pointed margin texture'
    - 'C2.4: Posterior is a vertex'
  C3:
    <<: *Taxonomy_defaults
    placeholder: 'C3: Posterior Margin Micro Texture'
    choices:
    - 'C3.0: Too broken to code'
    - 'C3.1: Smooth'
    - 'C3.2: Distinct serrated'
  D1:
    <<: *Taxonomy_defaults
    placeholder: 'D1: Planes of Symmetry'
    choices:
    - 'D1.0: Too broken to code'
    - 'D1.1: nan'
    - 'D1.2: one'
    - 'D1.3: two'
    - 'D1.4: radial'
  E1:
    <<: *Taxonomy_defaults
    placeholder: 'E1: # of cusps'
    choices:
    - 'E1.0: Too broken to code'
    - 'E1.1: nan'
    - 'E1.2: one'
    - 'E1.3: two'
    - 'E1.4: three'
    - 'E1.5: four'
    - 'E1.6: five'
    - 'E1.7: six'
    - 'E1.8: seven'
    - 'E1.9: eight'
    - 'E1.10: nine'
    - 'E1.11: ten or more'
  E2:
    <<: *Taxonomy_defaults
    placeholder: 'E2: Cusps definition'
    choices:
    - 'E2.0: No cusps or too broken to code'
    - 'E2.1: Ridges not associated with cusps'
    - 'E2.2: Cusps defined by ridges'
    - 'E2.3: Some cusps defined by ridges/some ridges associated with cusps'
  E3:
    <<: *Taxonomy_defaults
    placeholder: 'E3: Cusp Similarity'
    choices:
    - 'E3.0: No cusps/one cusp or too broken to code'
    - 'E3.1: Cusps are same length/width/shape'
    - 'E3.2: Central cusp is distinct'
    - 'E3.3: cusps opposite each other are similar, cusps next to each other are distinct'
    - 'E3.4: Irregular'
  E4:
    <<: *Taxonomy_defaults
    placeholder: 'E4: Cusp Relative Length'
    choices:
    - 'E4.0: No cusps or too broken to code'
    - "E4.1: ¼ > x"
    - "E4.2: ¼ < x < ½"
    - "E4.3: ½ < x"
  F1:
    <<: *Taxonomy_defaults
    placeholder: 'F1: Ridge System'
    choices:
    - 'F1.0: Too broken to code'
    - 'F1.1: Smooth'
    - 'F1.2: Linear (can tell directionality-anterior/posterior, ridges only curve
      in a max. 1 way-not wavy)'
    - 'F1.3: Geometric (Central branching pattern)'
    - 'F1.4: Meandering ridges (ridges curve or intersect in more than 1 way/direction)'
    - 'F1.5: Spine'
    - 'F1.6: Branching (can tell directionality but ridges curve or intersect in more
      than 1 way)'
  G1:
    <<: *Taxonomy_defaults
    placeholder: 'G1: Number of ridge segments'
    choices:
    - 'G1.0: Too broken to code'
    - 'G1.1: nan'
    - 'G1.2: one'
    - 'G1.3: two'
    - 'G1.4: three'
    - 'G1.5: four'
    - 'G1.6: five'
    - 'G1.7: six-ten'
    - 'G1.8: eleven or more'
  G2:
    <<: *Taxonomy_defaults
    placeholder: 'G2: Number of independent ridges'
    choices:
    - 'G2.0: Too broken to code'
    - 'G2.1: nan'
    - 'G2.2: one'
    - 'G2.3: two'
    - 'G2.4: three'
    - 'G2.5: four'
    - 'G2.6: five'
    - 'G2.7: six or more'
  G3:
    <<: *Taxonomy_defaults
    placeholder: 'G3: Ridge outgrowths'
    choices:
    - 'G3.0: no ridges or too broken to code'
    - 'G3.1: no ridge outgrowths'
    - 'G3.2: one ridge outgrowth'
    - 'G3.3: two ridge outgrowths'
  H1:
    <<: *Taxonomy_defaults
    placeholder: 'H1: Ridge Orientation'
    choices:
    - 'H1.0: Only one Ridge/No Ridges or too broken to code'
    - 'H1.1: Parallel'
    - 'H1.2: Converges from anterior'
    - 'H1.3: Diverges from anterior'
    - 'H1.4: Diverges then converges'
    - 'H1.5: Ridges intesect/branch'
    - 'H1.6: Apex Radial (spine)'
    - 'H1.7: Irregular/other/no discernable anterior/posterior'
    - 'H1.8: Multiple'
  I1:
    <<: *Taxonomy_defaults
    placeholder: 'I1: Central Ridge(s) or trough Disparity'
    choices:
    - 'I1.0: No ridges or too broken to code'
    - 'I1.1: No central ridge'
    - 'I1.2: Only one Ridge'
    - 'I1.3: Same as other ridges'
    - 'I1.4: Distinct shape/size from other ridges'
  I2:
    <<: *Taxonomy_defaults
    placeholder: 'I2: Central Ridge Directionality'
    choices:
    - 'I2.0: None or too broken to code'
    - 'I2.1: Straight'
    - 'I2.2: Curved'
    - 'I2.3: Meandering'
  I3:
    <<: *Taxonomy_defaults
    placeholder: 'I3: Central Ridge Width'
    choices:
    - 'I3.0: None or too broken to code'
    - 'I3.1: Parallel'
    - 'I3.2: Triangular widening from anterior'
    - 'I3.3: Triangular thinning from anterior'
    - 'I3.4: Diamond-like'
    - 'I3.5: Creates a Central Trough'
    - 'I3.6: Irregular'
  J1:
    <<: *Taxonomy_defaults
    placeholder: 'J1: Non-Central Ridge Directionality'
    choices:
    - 'J1.0: None/only one ridge or too broken to code'
    - 'J1.1: Straight'
    - 'J1.2: Concave Curved'
    - 'J1.3: Convex Curved'
    - 'J1.4: Meandering'
    - 'J1.5: Combination'
  J2:
    <<: *Taxonomy_defaults
    placeholder: 'J2: Non Central Ridge Width'
    choices:
    - 'J2.0: None or too broken to code'
    - 'J2.1: Parallel'
    - 'J2.2: Triangular widening from anterior'
    - 'J2.3: Triangular thinning from anterior'
    - 'J2.4: Diamond-like'
    - 'J2.5: Creates Troughs'
    - 'J2.6: Irregular/ Combination'
  K1:
    <<: *Taxonomy_defaults
    placeholder: 'K1: Central Ridge System Shape'
    choices:
    - 'K1.0: No Ridges or too broken to code'
    - 'K1.1: Ridges present but no central shape observed'
    - 'K1.2: Circular/oval'
    - 'K1.3: Triangular'
    - 'K1.4: Quadrilateral'
    - 'K1.5: Pentagonal'
    - 'K1.6: Hexagon'
    - 'K1.7: Heptagon'
    - 'K1.8: Mound'
    - 'K1.9: Octagon'
    - 'K1.10: Multiple'
    - 'K1.11: Irregular'
  K2:
    <<: *Taxonomy_defaults
    placeholder: 'K2: Central Ridge System Shape planes of symmetry'
    choices:
    - 'K2.0: No central shape or too broken to code'
    - 'K2.1: central shape but no plane of symmetry'
    - 'K2.2: one'
    - 'K2.3: two'
    - 'K2.4: radial'
  L1:
    <<: *Taxonomy_defaults
    placeholder: 'L1: Ridge length'
    choices:
    - 'L1.0: Too broken to code'
    - 'L1.1: No Ridges'
    - 'L1.2: Ridge length=lateral length'
    - 'L1.3: Ridge ends mid crown/ Ridge begins mid crown'
    - 'L1.4: Ridge begins and ends mid crown'
    - 'L1.5: Includes ridges described by a combination of 1,2,3'
  L2:
    <<: *Taxonomy_defaults
    placeholder: 'L2: Ridge Definition'
    choices:
    - 'L2.0: No Ridges or too broken to code'
    - 'L2.1: Not Clearly Defined'
    - 'L2.2: Clearly defined on part of the crown but gets shallower and does not
      extend to full length of denticle'
    - 'L2.3: Clearly Defined'
    - 'L2.4: Only the central ridge is clearly defined'
  L3:
    <<: *Taxonomy_defaults
    placeholder: 'L3: Ridge/Ridge Height'
    choices:
    - 'L3.0: None or too broken to code'
    - 'L3.1: Only one ridge'
    - 'L3.2: equal ridge heights'
    - 'L3.3: Variable ridge height'
  L4:
    <<: *Taxonomy_defaults
    placeholder: 'L4: Ridge/Trough Angularity'
    choices:
    - 'L4.0: No ridges or too broken to code'
    - 'L4.1: Ridge profiles or trough are rounded'
    - 'L4.2: Ridge profiles or troughs are triangular'
    - 'L4.3: Ridge profiles or troughs are funnel shapes (rounded with a skinnier
      point)'
    - 'L4.4: Ridge profiles or troughs are variable or described by another shape'
    - 'L4.5: Ridge profiles or troughs are rectangular'
  M1:
    <<: *Taxonomy_defaults
    placeholder: 'M1: # of depression'
    choices:
    - 'M1.0: Too broken to code'
    - 'M1.1: nan'
    - 'M1.2: one'
    - 'M1.3: two'
    - 'M1.4: three'
    - 'M1.5: four'
    - 'M1.6: five or more'
    - "M1.7: Multiple depressions (>2) but denticle is broken so unable to discern precise number"
  M2:
    <<: *Taxonomy_defaults
    placeholder: 'M2: Depression(s) type'
    choices:
    - 'M2.0: No depression or too broken to code'
    - 'M2.1: Thumbprint (surface layer)'
    - 'M2.2: Open tunnel (partially covered)'
    - 'M2.3: Dimples (depressions surrounded by ridges)'
  M3:
    <<: *Taxonomy_defaults
    placeholder: 'M3: Location of depression'
    choices:
    - 'M3.0: No depression or too broken to code'
    - 'M3.1: Central depression'
    - 'M3.2: Close to edge depression'
    - 'M3.3: Both central and edge depressions'
  M4:
    <<: *Taxonomy_defaults
    placeholder: 'M4: Shape of dimple(s)'
    choices:
    - 'M4.0: none or too broken to code'
    - 'M4.1: circle'
    - 'M4.2: Elongated'
    - 'M4.3: Teardrop (smooth curve)'
    - 'M4.4: Square/quadrilateral'
    - 'M4.5: Pentagon'
    - 'M4.6: Irregular'
    - 'M4.7: Multiple different shapes'
  N1:
    <<: *Taxonomy_defaults
    placeholder: 'N1: Secondary Ridge Features'
    choices:
    - 'N1.0: Too broken to code'
    - 'N1.1: No Ridges'
    - 'N1.2: No secondary ridge features'
    - 'N1.3: Micro-reliefs on ridges'
    - 'N1.4: Honeycomb surface texture'
    - 'N1.5: Wavy surface texture'
    - 'N1.6: Honeycomb/wavey combination surface texture'
    - 'N1.7: Vertical protrusion(s) on ridges'
    - 'N1.8: Pockmarks'
  N2:
    <<: *Taxonomy_defaults
    placeholder: 'N2: Surface Texture Location'
    choices:
    - 'N2.0: None/too broken to code'
    - 'N2.1: Ridges only'
    - 'N2.2: Crown and ridges'
    - 'N2.3: Crown except ridges'
    - 'N2.4: Anterior of crown only'
    - 'N2.5: Middle of crown only'
    - 'N2.6: Posterior of crown only'
    - 'N2.7: Edges of crown only'
  N3:
    <<: *Taxonomy_defaults
    placeholder: 'N3: Surface Texture Coverage'
    choices:
    - 'N3.0: None/too broken to code'
    - 'N3.1: Less than 30%'
    - 'N3.2: Between 30% and 70%'
    - 'N3.3: Greater than 70%'
  O1:
    <<: *Taxonomy_defaults
    placeholder: 'O1: Overall base shape'
    choices:
    - 'O1.0: Base not preserved/too broken to code'
    - 'O1.1: Kite shaped'
    - 'O1.2: Kite/cruciform shaped'
    - 'O1.3: Kite/cruciform shaped missing 1/4 of the cross ridges/extensions'
    - 'O1.4: Rhombus shaped'
    - 'O1.5: Rounded rhombus'
    - 'O1.6: Stretched rhombus'
    - 'O1.7: Trapazoid/rhombus hybrid (rhombus like but with a flat anterior edge)'
    - 'O1.8: Oval/oval like'
    - 'O1.9: Circular'
    - 'O1.10: Tree roots (irregular with many radiating ridges)'
    - 'O1.11: Mirrors crown shape'
    - 'O1.12: Base mirrors crown shape and there is no distinct separation between
      crown and base (no peduncle)'
  O2:
    <<: *Taxonomy_defaults
    placeholder: 'O2: Base width/length'
    choices:
    - 'O2.0: Base not preserved/too broken to code'
    - 'O2.1: Equal width and length'
    - 'O2.2: Wider than long'
    - 'O2.3: Longer than wide'
    - 'O2.4: Unequal width and length (no directionality)'
  O3:
    <<: *Taxonomy_defaults
    placeholder: 'O3: Crown to base ratio'
    choices:
    - 'O3.0: Base not preserved/too broken to code'
    - 'O3.1: Crown and base have the same area'
    - 'O3.2: Crown has a larger area'
    - 'O3.3: Base has a larger area'
  O4:
    <<: *Taxonomy_defaults
    placeholder: 'O4: Number of Grooves'
    choices:
    - 'O4.0: Base not preserved/too broken to code'
    - 'O4.1: No grooves, completely rounded/smooth'
    - 'O4.2: One'
    - 'O4.3: Two'
    - 'O4.4: Three'
    - 'O4.5: Four'
    - 'O4.6: Five'
    - 'O4.7: Six (plus)'
  O5:
    <<: *Taxonomy_defaults
    placeholder: 'O5: Root foramen opening shape'
    choices:
    - 'O5.0: Base not preserved/too broken to code'
    - 'O5.1: No root opening'
    - 'O5.2: Rhombus'
    - 'O5.3: Elipse'
    - 'O5.4: Arc'
    - 'O5.5: Mirrors base shape with more rounded edges'
  O6:
    <<: *Taxonomy_defaults
    placeholder: 'O6: Root foramen location'
    choices:
    - 'O6.0: No root opening or base not preserved/too broken to code'
    - 'O6.1: Center of base'
    - 'O6.2: Anterior of base'
    - 'O6.3: Posterior of base'
  O7:
    <<: *Taxonomy_defaults
    placeholder: 'O7: Peduncle height:width'
    choices:
    - 'O7.0: Base not preserved/too broken to code'
    - 'O7.1: Equal width and height'
    - 'O7.2: Wider than height'
    - 'O7.3: Higher than width'
    - 'O7.4: No Peduncle (sits flat on surface)'
  O8:
    <<: *Taxonomy_defaults
    placeholder: 'O8: Crown:root angle'
    choices:
    - 'O8.0: Base not preserved/too broken to code'
    - 'O8.1: Perpendicular (Crown pointing directly up from base, e.g. spine)'
    - 'O8.2: Obtuse (Crown pointing away from base)'
    - 'O8.3: Parallel (Crown directly over Base)'
    - 'O8.4: Acute (Crown pointing towards base)'
  O9:
    <<: *Taxonomy_defaults
    placeholder: 'O9: Base to crown connection location'
    choices:
    - 'O9.0: Base not preserved/too broken to code'
    - 'O9.1: at anterior of crown'
    - 'O9.2: at center of crown'
    - 'O9.3: at posterior of crown'
  O10:
    <<: *Taxonomy_defaults
    placeholder: 'O10: Mound'
    choices:
    - 'O10.0: Base not preserved/too broken to code'
    - 'O10.1: Not mounded'
    - 'O10.2: Mounded'
